FROM php:8.1.16-fpm

ARG NODE_VERSION=18

LABEL maintainer="APP PARKING SYSTEM"

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions \
    && install-php-extensions @composer \
    gd \
    curl \
    pdo \
    pdo_mysql \
    mbstring \
    xml \
    zip \
    bcmath \
    intl \
    readline \
    msgpack \
    igbinary \
    redis

RUN curl -sLS https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm

